version: "3.3"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    env_file:
      - .env.docker


  app:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app 
    env_file:
      - .env.docker
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - db




